package org.bigdata.zczw.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import java.io.Serializable;

/**
 * Entity mapped to table USER.
 */
public class User implements Serializable {

    private Long userid;
    private String username;
    private String usersex;
    private String token;
    private String zwtoken;
    private String userphone;
    private String imagePosition;
    private String positionName;
    private String categoryName;
    private String jobsName;
    private String unitsName;
    private String prilLevelName;
    private String prilLevel;

    public User() {
    }

    public User(String username) {
        this.username = username;
    }

    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsersex() {
        return usersex;
    }

    public void setUsersex(String usersex) {
        this.usersex = usersex;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getZwtoken() {
        return zwtoken;
    }

    public void setZwtoken(String zwtoken) {
        this.zwtoken = zwtoken;
    }

    public String getUserphone() {
        return userphone;
    }

    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    public String getImagePosition() {
        return imagePosition;
    }

    public void setImagePosition(String imagePosition) {
        this.imagePosition = imagePosition;
    }

    public String getPositionName() {
        return positionName;
    }

    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getJobsName() {
        return jobsName;
    }

    public void setJobsName(String jobsName) {
        this.jobsName = jobsName;
    }

    public String getUnitsName() {
        return unitsName;
    }

    public void setUnitsName(String unitsName) {
        this.unitsName = unitsName;
    }

    public String getPrilLevelName() {
        return prilLevelName;
    }

    public void setPrilLevelName(String prilLevelName) {
        this.prilLevelName = prilLevelName;
    }

    public String getPrilLevel() {
        return prilLevel;
    }

    public void setPrilLevel(String prilLevel) {
        this.prilLevel = prilLevel;
    }

    @Override
    public String toString() {
        return "User{" +
                ", userid=" + userid +
                ", username='" + username + '\'' +
                ", imagePosition='" + imagePosition + '\'' +
                '}';
    }
}
